### ISSUE TITLE
call_packmol() does not generate mixture.xyz file

### ISSUE THREAD

**Issue by adelaiden** [aykol/mpmorph#13]
Hi, I've been trying to use this package to generate an amorphous structure. Right now, I'm just trying the example code in the readme file. I keep getting an error at the same point: when I call `structure = get_random_packed('Li', target_atoms=100)`, I get an error from the call_packmol() function saying that there is no mixture.xyz file. I can generate the packmol.input file, but from reading the code I don't see how the function is invoking packmol or how the mixture.xyz file should be generated. Any suggestions on what to do here?

Also, as a side note, the import statements should read
from `mpmorph.workflows.converge import get_converge_wf`
rather than `from mpmorph.workflow.converge import get_converge_wf`
since the folder was renamed "workflows".

**Comment by adelaiden** [comment]
Nevermind, I got this to work. My path was pointing to the packmol folder, but it needed to point to the executable within the folder.

**Comment by sivonxay** [comment]
Thanks for the comments. Glad you were able to get it to work. I have updated the readme to make it more obvious that the executable must be linked.
